### ISSUE TITLE
API Compatibility

### ISSUE THREAD

**Issue by median-man** [jmoniz155/my-trip-journal#34]
Please check-in with me about your api. Lets ensure you have a solid understanding of how to integrate it without running into cors or other issues when you deploy.

**Comment by jmoniz155** [comment]
Hey Jon so we had alittle confusion Kalani was working on 1 api and I was working on another, but we figured out all we need is 1 api and just getting a picture from it. So Kalani took over the api and I jumped on trip.handlebars trying to display a picture, placeholder for location, date and rating as well as the placeholder for the answers from the previous page. I believe I’m on the right track, we will see today

Thanks for checking in on me
